// <auto-generated />
namespace Autos4Sale.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newmodelsadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmodelsadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201710021735191_new models added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
