// <auto-generated />
namespace Autos4Sale.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makerenamedtobrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makerenamedtobrand));
        
        string IMigrationMetadata.Id
        {
            get { return "201710040936356_make renamed to brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
